var EmployeeAbsenceInfo = require('ComplexType/EmployeeAbsenceInfo')
var EmployeeAbsenceInfoCollection = require('ComplexType/EmployeeAbsenceInfoCollection')
var EmployeeEducationInfo = require('ComplexType/EmployeeEducationInfo')
var EmployeeEducationInfoCollection = require('ComplexType/EmployeeEducationInfoCollection')
var EmployeeReviewsInfo = require('ComplexType/EmployeeReviewsInfo')
var EmployeeReviewsInfoCollection = require('ComplexType/EmployeeReviewsInfoCollection')
var EmployeePreviousEmpoymentInfo = require('ComplexType/EmployeePreviousEmpoymentInfo')
var EmployeePreviousEmpoymentInfoCollection = require('ComplexType/EmployeePreviousEmpoymentInfoCollection')
var EmployeeRolesInfo = require('ComplexType/EmployeeRolesInfo')
var EmployeeRolesInfoCollection = require('ComplexType/EmployeeRolesInfoCollection')
var EmployeeSavingsPaymentInfo = require('ComplexType/EmployeeSavingsPaymentInfo')
var EmployeeSavingsPaymentInfoCollection = require('ComplexType/EmployeeSavingsPaymentInfoCollection')
var EmployeeBranchAssignmentItem = require('ComplexType/EmployeeBranchAssignmentItem')
var EmployeeBranchAssignmentItemCollection = require('ComplexType/EmployeeBranchAssignmentItemCollection')

var BoGenderTypes = require('EnumType/BoGenderTypes')
var BoSalaryCostUnits = require('EnumType/BoSalaryCostUnits')
var BoMeritalStatuses = require('EnumType/BoMeritalStatuses')
var EmployeeExemptionUnitEnum = require('EnumType/EmployeeExemptionUnitEnum')
var BoYesNoEnum = require('EnumType/BoYesNoEnum')
var EmployeePaymentMethodEnum = require('EnumType/EmployeePaymentMethodEnum')
var SPEDContabilQualificationCodeEnum = require('EnumType/SPEDContabilQualificationCodeEnum')

var ServiceLayerModule = require('Base/ServiceLayerModule.js');

//workaround the possible intellisense bug of VS
if (typeof (SAPB1) === "undefined") {
    SAPB1 = {};
}

SAPB1.EmployeeInfo = function () {
}
SAPB1.EmployeeInfo.prototype = new SAPB1.EntityType();
SAPB1.EmployeeInfo.prototype.constructor = SAPB1.EmployeeInfo;
SAPB1.EmployeeInfo.prototype.keys.push('EmployeeID');
SAPB1.EmployeeInfo.EmployeeID = { valueOf: function(){return 'EmployeeID';}, Type: 'Edm.Int32', Index: 0, Nullable: false, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.LastName = { valueOf: function(){return 'LastName';}, Type: 'Edm.String', Index: 1, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.FirstName = { valueOf: function(){return 'FirstName';}, Type: 'Edm.String', Index: 2, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.MiddleName = { valueOf: function(){return 'MiddleName';}, Type: 'Edm.String', Index: 3, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Gender = { valueOf: function(){return 'Gender';}, Type: 'BoGenderTypes', Index: 4, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.JobTitle = { valueOf: function(){return 'JobTitle';}, Type: 'Edm.String', Index: 5, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.EmployeeType = { valueOf: function(){return 'EmployeeType';}, Type: 'Edm.Int32', Index: 6, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Department = { valueOf: function(){return 'Department';}, Type: 'Edm.Int32', Index: 7, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Branch = { valueOf: function(){return 'Branch';}, Type: 'Edm.Int32', Index: 8, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkStreet = { valueOf: function(){return 'WorkStreet';}, Type: 'Edm.String', Index: 9, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkBlock = { valueOf: function(){return 'WorkBlock';}, Type: 'Edm.String', Index: 10, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkZipCode = { valueOf: function(){return 'WorkZipCode';}, Type: 'Edm.String', Index: 11, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkCity = { valueOf: function(){return 'WorkCity';}, Type: 'Edm.String', Index: 12, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkCounty = { valueOf: function(){return 'WorkCounty';}, Type: 'Edm.String', Index: 13, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkCountryCode = { valueOf: function(){return 'WorkCountryCode';}, Type: 'Edm.String', Index: 14, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkStateCode = { valueOf: function(){return 'WorkStateCode';}, Type: 'Edm.String', Index: 15, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Manager = { valueOf: function(){return 'Manager';}, Type: 'Edm.Int32', Index: 16, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.ApplicationUserID = { valueOf: function(){return 'ApplicationUserID';}, Type: 'Edm.Int32', Index: 17, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.SalesPersonCode = { valueOf: function(){return 'SalesPersonCode';}, Type: 'Edm.Int32', Index: 18, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.OfficePhone = { valueOf: function(){return 'OfficePhone';}, Type: 'Edm.String', Index: 19, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.OfficeExtension = { valueOf: function(){return 'OfficeExtension';}, Type: 'Edm.String', Index: 20, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.MobilePhone = { valueOf: function(){return 'MobilePhone';}, Type: 'Edm.String', Index: 21, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Pager = { valueOf: function(){return 'Pager';}, Type: 'Edm.String', Index: 22, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomePhone = { valueOf: function(){return 'HomePhone';}, Type: 'Edm.String', Index: 23, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Fax = { valueOf: function(){return 'Fax';}, Type: 'Edm.String', Index: 24, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.eMail = { valueOf: function(){return 'eMail';}, Type: 'Edm.String', Index: 25, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.StartDate = { valueOf: function(){return 'StartDate';}, Type: 'Edm.DateTime', Index: 26, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.StatusCode = { valueOf: function(){return 'StatusCode';}, Type: 'Edm.Int32', Index: 27, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Salary = { valueOf: function(){return 'Salary';}, Type: 'Edm.Double', Index: 28, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.SalaryUnit = { valueOf: function(){return 'SalaryUnit';}, Type: 'BoSalaryCostUnits', Index: 29, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.EmployeeCosts = { valueOf: function(){return 'EmployeeCosts';}, Type: 'Edm.Double', Index: 30, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.EmployeeCostUnit = { valueOf: function(){return 'EmployeeCostUnit';}, Type: 'BoSalaryCostUnits', Index: 31, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.TerminationDate = { valueOf: function(){return 'TerminationDate';}, Type: 'Edm.DateTime', Index: 32, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.TreminationReason = { valueOf: function(){return 'TreminationReason';}, Type: 'Edm.Int32', Index: 33, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.BankCode = { valueOf: function(){return 'BankCode';}, Type: 'Edm.String', Index: 34, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.BankBranch = { valueOf: function(){return 'BankBranch';}, Type: 'Edm.String', Index: 35, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.BankBranchNum = { valueOf: function(){return 'BankBranchNum';}, Type: 'Edm.String', Index: 36, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.BankAccount = { valueOf: function(){return 'BankAccount';}, Type: 'Edm.String', Index: 37, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeStreet = { valueOf: function(){return 'HomeStreet';}, Type: 'Edm.String', Index: 38, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeBlock = { valueOf: function(){return 'HomeBlock';}, Type: 'Edm.String', Index: 39, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeZipCode = { valueOf: function(){return 'HomeZipCode';}, Type: 'Edm.String', Index: 40, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeCity = { valueOf: function(){return 'HomeCity';}, Type: 'Edm.String', Index: 41, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeCounty = { valueOf: function(){return 'HomeCounty';}, Type: 'Edm.String', Index: 42, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeCountry = { valueOf: function(){return 'HomeCountry';}, Type: 'Edm.String', Index: 43, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeState = { valueOf: function(){return 'HomeState';}, Type: 'Edm.String', Index: 44, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.DateOfBirth = { valueOf: function(){return 'DateOfBirth';}, Type: 'Edm.DateTime', Index: 45, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CountryOfBirth = { valueOf: function(){return 'CountryOfBirth';}, Type: 'Edm.String', Index: 46, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.MartialStatus = { valueOf: function(){return 'MartialStatus';}, Type: 'BoMeritalStatuses', Index: 47, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.NumOfChildren = { valueOf: function(){return 'NumOfChildren';}, Type: 'Edm.Int32', Index: 48, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.IdNumber = { valueOf: function(){return 'IdNumber';}, Type: 'Edm.String', Index: 49, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CitizenshipCountryCode = { valueOf: function(){return 'CitizenshipCountryCode';}, Type: 'Edm.String', Index: 50, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PassportNumber = { valueOf: function(){return 'PassportNumber';}, Type: 'Edm.String', Index: 51, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PassportExpirationDate = { valueOf: function(){return 'PassportExpirationDate';}, Type: 'Edm.DateTime', Index: 52, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Picture = { valueOf: function(){return 'Picture';}, Type: 'Edm.String', Index: 53, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Remarks = { valueOf: function(){return 'Remarks';}, Type: 'Edm.String', Index: 54, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.SalaryCurrency = { valueOf: function(){return 'SalaryCurrency';}, Type: 'Edm.String', Index: 55, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.EmployeeCostsCurrency = { valueOf: function(){return 'EmployeeCostsCurrency';}, Type: 'Edm.String', Index: 56, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkBuildingFloorRoom = { valueOf: function(){return 'WorkBuildingFloorRoom';}, Type: 'Edm.String', Index: 57, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeBuildingFloorRoom = { valueOf: function(){return 'HomeBuildingFloorRoom';}, Type: 'Edm.String', Index: 58, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Position = { valueOf: function(){return 'Position';}, Type: 'Edm.Int32', Index: 59, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.AttachmentEntry = { valueOf: function(){return 'AttachmentEntry';}, Type: 'Edm.Int32', Index: 60, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CostCenterCode = { valueOf: function(){return 'CostCenterCode';}, Type: 'Edm.String', Index: 61, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CompanyNumber = { valueOf: function(){return 'CompanyNumber';}, Type: 'Edm.String', Index: 62, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.VacationPreviousYear = { valueOf: function(){return 'VacationPreviousYear';}, Type: 'Edm.Int32', Index: 63, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.VacationCurrentYear = { valueOf: function(){return 'VacationCurrentYear';}, Type: 'Edm.Int32', Index: 64, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.MunicipalityKey = { valueOf: function(){return 'MunicipalityKey';}, Type: 'Edm.String', Index: 65, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.TaxClass = { valueOf: function(){return 'TaxClass';}, Type: 'Edm.String', Index: 66, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.IncomeTaxLiability = { valueOf: function(){return 'IncomeTaxLiability';}, Type: 'Edm.String', Index: 67, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Religion = { valueOf: function(){return 'Religion';}, Type: 'Edm.String', Index: 68, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PartnerReligion = { valueOf: function(){return 'PartnerReligion';}, Type: 'Edm.String', Index: 69, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.ExemptionAmount = { valueOf: function(){return 'ExemptionAmount';}, Type: 'Edm.Double', Index: 70, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.ExemptionUnit = { valueOf: function(){return 'ExemptionUnit';}, Type: 'EmployeeExemptionUnitEnum', Index: 71, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.ExemptionCurrency = { valueOf: function(){return 'ExemptionCurrency';}, Type: 'Edm.String', Index: 72, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.AdditionalAmount = { valueOf: function(){return 'AdditionalAmount';}, Type: 'Edm.Double', Index: 73, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.AdditionalUnit = { valueOf: function(){return 'AdditionalUnit';}, Type: 'EmployeeExemptionUnitEnum', Index: 74, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.AdditionalCurrency = { valueOf: function(){return 'AdditionalCurrency';}, Type: 'Edm.String', Index: 75, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.TaxOfficeName = { valueOf: function(){return 'TaxOfficeName';}, Type: 'Edm.String', Index: 76, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.TaxOfficeNumber = { valueOf: function(){return 'TaxOfficeNumber';}, Type: 'Edm.String', Index: 77, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HealthInsuranceName = { valueOf: function(){return 'HealthInsuranceName';}, Type: 'Edm.String', Index: 78, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HealthInsuranceCode = { valueOf: function(){return 'HealthInsuranceCode';}, Type: 'Edm.String', Index: 79, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HealthInsuranceType = { valueOf: function(){return 'HealthInsuranceType';}, Type: 'Edm.String', Index: 80, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.SocialInsuranceNumber = { valueOf: function(){return 'SocialInsuranceNumber';}, Type: 'Edm.String', Index: 81, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.ProfessionStatus = { valueOf: function(){return 'ProfessionStatus';}, Type: 'Edm.String', Index: 82, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.EducationStatus = { valueOf: function(){return 'EducationStatus';}, Type: 'Edm.String', Index: 83, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PersonGroup = { valueOf: function(){return 'PersonGroup';}, Type: 'Edm.String', Index: 84, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.JobTitleCode = { valueOf: function(){return 'JobTitleCode';}, Type: 'Edm.String', Index: 85, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.BankCodeForDATEV = { valueOf: function(){return 'BankCodeForDATEV';}, Type: 'Edm.String', Index: 86, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.DeviatingBankAccountOwner = { valueOf: function(){return 'DeviatingBankAccountOwner';}, Type: 'BoYesNoEnum', Index: 87, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.SpouseFirstName = { valueOf: function(){return 'SpouseFirstName';}, Type: 'Edm.String', Index: 88, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.SpouseSurname = { valueOf: function(){return 'SpouseSurname';}, Type: 'Edm.String', Index: 89, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.ExternalEmployeeNumber = { valueOf: function(){return 'ExternalEmployeeNumber';}, Type: 'Edm.String', Index: 90, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.BirthPlace = { valueOf: function(){return 'BirthPlace';}, Type: 'Edm.String', Index: 91, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PaymentMethod = { valueOf: function(){return 'PaymentMethod';}, Type: 'EmployeePaymentMethodEnum', Index: 92, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.STDCode = { valueOf: function(){return 'STDCode';}, Type: 'Edm.Int32', Index: 93, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CPF = { valueOf: function(){return 'CPF';}, Type: 'Edm.String', Index: 94, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CRCNumber = { valueOf: function(){return 'CRCNumber';}, Type: 'Edm.String', Index: 95, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.AccountantResponsible = { valueOf: function(){return 'AccountantResponsible';}, Type: 'BoYesNoEnum', Index: 96, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.LegalRepresentative = { valueOf: function(){return 'LegalRepresentative';}, Type: 'BoYesNoEnum', Index: 97, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.DIRFResponsible = { valueOf: function(){return 'DIRFResponsible';}, Type: 'BoYesNoEnum', Index: 98, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CRCState = { valueOf: function(){return 'CRCState';}, Type: 'Edm.String', Index: 99, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.Active = { valueOf: function(){return 'Active';}, Type: 'BoYesNoEnum', Index: 100, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.IDType = { valueOf: function(){return 'IDType';}, Type: 'Edm.String', Index: 101, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.BPLID = { valueOf: function(){return 'BPLID';}, Type: 'Edm.Int32', Index: 102, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PassportIssueDate = { valueOf: function(){return 'PassportIssueDate';}, Type: 'Edm.DateTime', Index: 103, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PassportIssuer = { valueOf: function(){return 'PassportIssuer';}, Type: 'Edm.String', Index: 104, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.QualificationCode = { valueOf: function(){return 'QualificationCode';}, Type: 'SPEDContabilQualificationCodeEnum', Index: 105, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PRWebAccess = { valueOf: function(){return 'PRWebAccess';}, Type: 'BoYesNoEnum', Index: 106, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.PreviousPRWebAccess = { valueOf: function(){return 'PreviousPRWebAccess';}, Type: 'BoYesNoEnum', Index: 107, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.WorkStreetNumber = { valueOf: function(){return 'WorkStreetNumber';}, Type: 'Edm.String', Index: 108, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.HomeStreetNumber = { valueOf: function(){return 'HomeStreetNumber';}, Type: 'Edm.String', Index: 109, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.LinkedVendor = { valueOf: function(){return 'LinkedVendor';}, Type: 'Edm.String', Index: 110, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CreateDate = { valueOf: function(){return 'CreateDate';}, Type: 'Edm.DateTime', Index: 111, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.CreateTime = { valueOf: function(){return 'CreateTime';}, Type: 'Edm.Time', Index: 112, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.UpdateDate = { valueOf: function(){return 'UpdateDate';}, Type: 'Edm.DateTime', Index: 113, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.UpdateTime = { valueOf: function(){return 'UpdateTime';}, Type: 'Edm.Time', Index: 114, Nullable: true, IsArray: false, IsComplex: false };
SAPB1.EmployeeInfo.EmployeeAbsenceInfoLines = { valueOf: function(){return 'EmployeeAbsenceInfoLines';}, Type: 'EmployeeAbsenceInfo', Index: 115, Nullable: true, IsArray: true, IsComplex: true };
SAPB1.EmployeeInfo.EmployeeEducationInfoLines = { valueOf: function(){return 'EmployeeEducationInfoLines';}, Type: 'EmployeeEducationInfo', Index: 116, Nullable: true, IsArray: true, IsComplex: true };
SAPB1.EmployeeInfo.EmployeeReviewsInfoLines = { valueOf: function(){return 'EmployeeReviewsInfoLines';}, Type: 'EmployeeReviewsInfo', Index: 117, Nullable: true, IsArray: true, IsComplex: true };
SAPB1.EmployeeInfo.EmployeePreviousEmpoymentInfoLines = { valueOf: function(){return 'EmployeePreviousEmpoymentInfoLines';}, Type: 'EmployeePreviousEmpoymentInfo', Index: 118, Nullable: true, IsArray: true, IsComplex: true };
SAPB1.EmployeeInfo.EmployeeRolesInfoLines = { valueOf: function(){return 'EmployeeRolesInfoLines';}, Type: 'EmployeeRolesInfo', Index: 119, Nullable: true, IsArray: true, IsComplex: true };
SAPB1.EmployeeInfo.EmployeeSavingsPaymentInfoLines = { valueOf: function(){return 'EmployeeSavingsPaymentInfoLines';}, Type: 'EmployeeSavingsPaymentInfo', Index: 120, Nullable: true, IsArray: true, IsComplex: true };
SAPB1.EmployeeInfo.EmployeeBranchAssignment = { valueOf: function(){return 'EmployeeBranchAssignment';}, Type: 'EmployeeBranchAssignmentItem', Index: 121, Nullable: true, IsArray: true, IsComplex: true };
SAPB1.EmployeeInfo.prototype.EmployeeID = new Number();
SAPB1.EmployeeInfo.prototype.LastName = new String();
SAPB1.EmployeeInfo.prototype.FirstName = new String();
SAPB1.EmployeeInfo.prototype.MiddleName = new String();
SAPB1.EmployeeInfo.prototype.Gender = new String();
SAPB1.EmployeeInfo.prototype.JobTitle = new String();
SAPB1.EmployeeInfo.prototype.EmployeeType = new Number();
SAPB1.EmployeeInfo.prototype.Department = new Number();
SAPB1.EmployeeInfo.prototype.Branch = new Number();
SAPB1.EmployeeInfo.prototype.WorkStreet = new String();
SAPB1.EmployeeInfo.prototype.WorkBlock = new String();
SAPB1.EmployeeInfo.prototype.WorkZipCode = new String();
SAPB1.EmployeeInfo.prototype.WorkCity = new String();
SAPB1.EmployeeInfo.prototype.WorkCounty = new String();
SAPB1.EmployeeInfo.prototype.WorkCountryCode = new String();
SAPB1.EmployeeInfo.prototype.WorkStateCode = new String();
SAPB1.EmployeeInfo.prototype.Manager = new Number();
SAPB1.EmployeeInfo.prototype.ApplicationUserID = new Number();
SAPB1.EmployeeInfo.prototype.SalesPersonCode = new Number();
SAPB1.EmployeeInfo.prototype.OfficePhone = new String();
SAPB1.EmployeeInfo.prototype.OfficeExtension = new String();
SAPB1.EmployeeInfo.prototype.MobilePhone = new String();
SAPB1.EmployeeInfo.prototype.Pager = new String();
SAPB1.EmployeeInfo.prototype.HomePhone = new String();
SAPB1.EmployeeInfo.prototype.Fax = new String();
SAPB1.EmployeeInfo.prototype.eMail = new String();
SAPB1.EmployeeInfo.prototype.StartDate = new String();
SAPB1.EmployeeInfo.prototype.StatusCode = new Number();
SAPB1.EmployeeInfo.prototype.Salary = new Number();
SAPB1.EmployeeInfo.prototype.SalaryUnit = new String();
SAPB1.EmployeeInfo.prototype.EmployeeCosts = new Number();
SAPB1.EmployeeInfo.prototype.EmployeeCostUnit = new String();
SAPB1.EmployeeInfo.prototype.TerminationDate = new String();
SAPB1.EmployeeInfo.prototype.TreminationReason = new Number();
SAPB1.EmployeeInfo.prototype.BankCode = new String();
SAPB1.EmployeeInfo.prototype.BankBranch = new String();
SAPB1.EmployeeInfo.prototype.BankBranchNum = new String();
SAPB1.EmployeeInfo.prototype.BankAccount = new String();
SAPB1.EmployeeInfo.prototype.HomeStreet = new String();
SAPB1.EmployeeInfo.prototype.HomeBlock = new String();
SAPB1.EmployeeInfo.prototype.HomeZipCode = new String();
SAPB1.EmployeeInfo.prototype.HomeCity = new String();
SAPB1.EmployeeInfo.prototype.HomeCounty = new String();
SAPB1.EmployeeInfo.prototype.HomeCountry = new String();
SAPB1.EmployeeInfo.prototype.HomeState = new String();
SAPB1.EmployeeInfo.prototype.DateOfBirth = new String();
SAPB1.EmployeeInfo.prototype.CountryOfBirth = new String();
SAPB1.EmployeeInfo.prototype.MartialStatus = new String();
SAPB1.EmployeeInfo.prototype.NumOfChildren = new Number();
SAPB1.EmployeeInfo.prototype.IdNumber = new String();
SAPB1.EmployeeInfo.prototype.CitizenshipCountryCode = new String();
SAPB1.EmployeeInfo.prototype.PassportNumber = new String();
SAPB1.EmployeeInfo.prototype.PassportExpirationDate = new String();
SAPB1.EmployeeInfo.prototype.Picture = new String();
SAPB1.EmployeeInfo.prototype.Remarks = new String();
SAPB1.EmployeeInfo.prototype.SalaryCurrency = new String();
SAPB1.EmployeeInfo.prototype.EmployeeCostsCurrency = new String();
SAPB1.EmployeeInfo.prototype.WorkBuildingFloorRoom = new String();
SAPB1.EmployeeInfo.prototype.HomeBuildingFloorRoom = new String();
SAPB1.EmployeeInfo.prototype.Position = new Number();
SAPB1.EmployeeInfo.prototype.AttachmentEntry = new Number();
SAPB1.EmployeeInfo.prototype.CostCenterCode = new String();
SAPB1.EmployeeInfo.prototype.CompanyNumber = new String();
SAPB1.EmployeeInfo.prototype.VacationPreviousYear = new Number();
SAPB1.EmployeeInfo.prototype.VacationCurrentYear = new Number();
SAPB1.EmployeeInfo.prototype.MunicipalityKey = new String();
SAPB1.EmployeeInfo.prototype.TaxClass = new String();
SAPB1.EmployeeInfo.prototype.IncomeTaxLiability = new String();
SAPB1.EmployeeInfo.prototype.Religion = new String();
SAPB1.EmployeeInfo.prototype.PartnerReligion = new String();
SAPB1.EmployeeInfo.prototype.ExemptionAmount = new Number();
SAPB1.EmployeeInfo.prototype.ExemptionUnit = new String();
SAPB1.EmployeeInfo.prototype.ExemptionCurrency = new String();
SAPB1.EmployeeInfo.prototype.AdditionalAmount = new Number();
SAPB1.EmployeeInfo.prototype.AdditionalUnit = new String();
SAPB1.EmployeeInfo.prototype.AdditionalCurrency = new String();
SAPB1.EmployeeInfo.prototype.TaxOfficeName = new String();
SAPB1.EmployeeInfo.prototype.TaxOfficeNumber = new String();
SAPB1.EmployeeInfo.prototype.HealthInsuranceName = new String();
SAPB1.EmployeeInfo.prototype.HealthInsuranceCode = new String();
SAPB1.EmployeeInfo.prototype.HealthInsuranceType = new String();
SAPB1.EmployeeInfo.prototype.SocialInsuranceNumber = new String();
SAPB1.EmployeeInfo.prototype.ProfessionStatus = new String();
SAPB1.EmployeeInfo.prototype.EducationStatus = new String();
SAPB1.EmployeeInfo.prototype.PersonGroup = new String();
SAPB1.EmployeeInfo.prototype.JobTitleCode = new String();
SAPB1.EmployeeInfo.prototype.BankCodeForDATEV = new String();
SAPB1.EmployeeInfo.prototype.DeviatingBankAccountOwner = new String();
SAPB1.EmployeeInfo.prototype.SpouseFirstName = new String();
SAPB1.EmployeeInfo.prototype.SpouseSurname = new String();
SAPB1.EmployeeInfo.prototype.ExternalEmployeeNumber = new String();
SAPB1.EmployeeInfo.prototype.BirthPlace = new String();
SAPB1.EmployeeInfo.prototype.PaymentMethod = new String();
SAPB1.EmployeeInfo.prototype.STDCode = new Number();
SAPB1.EmployeeInfo.prototype.CPF = new String();
SAPB1.EmployeeInfo.prototype.CRCNumber = new String();
SAPB1.EmployeeInfo.prototype.AccountantResponsible = new String();
SAPB1.EmployeeInfo.prototype.LegalRepresentative = new String();
SAPB1.EmployeeInfo.prototype.DIRFResponsible = new String();
SAPB1.EmployeeInfo.prototype.CRCState = new String();
SAPB1.EmployeeInfo.prototype.Active = new String();
SAPB1.EmployeeInfo.prototype.IDType = new String();
SAPB1.EmployeeInfo.prototype.BPLID = new Number();
SAPB1.EmployeeInfo.prototype.PassportIssueDate = new String();
SAPB1.EmployeeInfo.prototype.PassportIssuer = new String();
SAPB1.EmployeeInfo.prototype.QualificationCode = new String();
SAPB1.EmployeeInfo.prototype.PRWebAccess = new String();
SAPB1.EmployeeInfo.prototype.PreviousPRWebAccess = new String();
SAPB1.EmployeeInfo.prototype.WorkStreetNumber = new String();
SAPB1.EmployeeInfo.prototype.HomeStreetNumber = new String();
SAPB1.EmployeeInfo.prototype.LinkedVendor = new String();
SAPB1.EmployeeInfo.prototype.CreateDate = new String();
SAPB1.EmployeeInfo.prototype.CreateTime = new String();
SAPB1.EmployeeInfo.prototype.UpdateDate = new String();
SAPB1.EmployeeInfo.prototype.UpdateTime = new String();
SAPB1.EmployeeInfo.prototype.EmployeeAbsenceInfoLines = new EmployeeAbsenceInfoCollection();
SAPB1.EmployeeInfo.prototype.EmployeeEducationInfoLines = new EmployeeEducationInfoCollection();
SAPB1.EmployeeInfo.prototype.EmployeeReviewsInfoLines = new EmployeeReviewsInfoCollection();
SAPB1.EmployeeInfo.prototype.EmployeePreviousEmpoymentInfoLines = new EmployeePreviousEmpoymentInfoCollection();
SAPB1.EmployeeInfo.prototype.EmployeeRolesInfoLines = new EmployeeRolesInfoCollection();
SAPB1.EmployeeInfo.prototype.EmployeeSavingsPaymentInfoLines = new EmployeeSavingsPaymentInfoCollection();
SAPB1.EmployeeInfo.prototype.EmployeeBranchAssignment = new EmployeeBranchAssignmentItemCollection();

SAPB1.EmployeeInfo.EmployeeAbsenceInfo = EmployeeAbsenceInfo
SAPB1.EmployeeInfo.EmployeeAbsenceInfoCollection = EmployeeAbsenceInfoCollection
SAPB1.EmployeeInfo.EmployeeEducationInfo = EmployeeEducationInfo
SAPB1.EmployeeInfo.EmployeeEducationInfoCollection = EmployeeEducationInfoCollection
SAPB1.EmployeeInfo.EmployeeReviewsInfo = EmployeeReviewsInfo
SAPB1.EmployeeInfo.EmployeeReviewsInfoCollection = EmployeeReviewsInfoCollection
SAPB1.EmployeeInfo.EmployeePreviousEmpoymentInfo = EmployeePreviousEmpoymentInfo
SAPB1.EmployeeInfo.EmployeePreviousEmpoymentInfoCollection = EmployeePreviousEmpoymentInfoCollection
SAPB1.EmployeeInfo.EmployeeRolesInfo = EmployeeRolesInfo
SAPB1.EmployeeInfo.EmployeeRolesInfoCollection = EmployeeRolesInfoCollection
SAPB1.EmployeeInfo.EmployeeSavingsPaymentInfo = EmployeeSavingsPaymentInfo
SAPB1.EmployeeInfo.EmployeeSavingsPaymentInfoCollection = EmployeeSavingsPaymentInfoCollection
SAPB1.EmployeeInfo.EmployeeBranchAssignmentItem = EmployeeBranchAssignmentItem
SAPB1.EmployeeInfo.EmployeeBranchAssignmentItemCollection = EmployeeBranchAssignmentItemCollection

SAPB1.EmployeeInfo.BoGenderTypes = BoGenderTypes
SAPB1.EmployeeInfo.BoSalaryCostUnits = BoSalaryCostUnits
SAPB1.EmployeeInfo.BoMeritalStatuses = BoMeritalStatuses
SAPB1.EmployeeInfo.EmployeeExemptionUnitEnum = EmployeeExemptionUnitEnum
SAPB1.EmployeeInfo.BoYesNoEnum = BoYesNoEnum
SAPB1.EmployeeInfo.EmployeePaymentMethodEnum = EmployeePaymentMethodEnum
SAPB1.EmployeeInfo.SPEDContabilQualificationCodeEnum = SPEDContabilQualificationCodeEnum

SAPB1.EmployeeInfo.create = function (rawObject) {
    var instance = new SAPB1.EmployeeInfo();
    for (var prop in rawObject) {
        if (rawObject.hasOwnProperty(prop)) {
            if (SAPB1.EmployeeInfo.prototype.hasOwnProperty(prop)) {
                if (instance[prop] instanceof SAPB1.Collection) {
                    var collectionInstance = instance[prop].constructor.create(rawObject[prop]);
                    instance[prop] = collectionInstance;
                } else if (instance[prop] instanceof SAPB1.ComplexType) {
                    var complexInstance = instance[prop].constructor.create(rawObject[prop]);
                    instance[prop] = complexInstance;
                }
                else {
                    instance[prop] = rawObject[prop];
                }
            }
        }
    }
    return instance;
}


module.exports = SAPB1.EmployeeInfo;
